In [6]:
import numpy as np
import torch

In [2]:
np.random.uniform(-1, 1)

ValueError: negative dimensions are not allowed

In [9]:
np.array([1, 0, 0, 0, 0, 0, 0, 0])

array([1, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.array([1, 0, 0, 0, 0, 0, 0, 0], dtype=float)

array([1., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
pref = torch.randn(3)
print(pref)
torch.distributions.Categorical(logits=pref).sample()

tensor([ 1.8639, -0.0808, -0.3276])


tensor(1)

In [24]:
a = np.array([0.5, 0.1])
(a < 0.2).all()

False

In [8]:
a = np.array([-1.5, 1.5])

In [9]:
np.clip(a, -1, 1)

array([-1.,  1.])

In [1]:
for t in range(-30, 0):
    print(t)

-30
-29
-28
-27
-26
-25
-24
-23
-22
-21
-20
-19
-18
-17
-16
-15
-14
-13
-12
-11
-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [7]:
np.cumsum([1,2,3,4,5])

array([ 1,  3,  6, 10, 15])