In [1]:
import numpy as np
import torch as tor

In [3]:
np.random.seed(0)
prefnp = np.random.randn(3)
pref = tor.tensor(prefnp, dtype=tor.float32, requires_grad=True)
pol = tor.distributions.Categorical(logits=pref)

In [4]:
prefnp

array([1.76405235, 0.40015721, 0.97873798])

In [5]:
pref

tensor([1.7641, 0.4002, 0.9787], requires_grad=True)

In [7]:
pol.probs

tensor([0.5842, 0.1494, 0.2664], grad_fn=<SoftmaxBackward>)

In [13]:
pol.sample()

tensor(0)

In [3]:
dist = tor.distributions.Normal(0, 1) 

In [17]:
eps = dist.sample()

In [18]:
eps

tensor(-0.9928)

In [19]:
tor.exp(dist.log_prob(eps))

tensor(0.2437)

In [29]:
tor.exp(dist.log_prob(tor.tensor(-0.1)))

tensor(0.3970)